#--
# Copyright (c) 2009-2010 Novell, Inc.
#
# All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of version 2 of the GNU General Public License
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, contact Novell, Inc.
#
# To contact Novell about this file by physical or electronic mail,
# you may find current contact information at www.novell.com
#++
require 'rake'
require 'fileutils'

# -*- ruby -*-
require File.join(File.dirname(__FILE__), 'config', 'rails_parent')
require File.join(RailsParent.parent, 'lib', 'tasks', 'common')
#import rake task files from plugins directory
Dir.glob(File.dirname(__FILE__) + "/lib/tasks/*.rake").each do |rake_file|
  import rake_file
end




include FileUtils::Verbose

#adapt to easyli local deploy of working plugin (for developement, release use rpm-based way)
desc "Deploy for development - run db:migrate, create basic dirs and install grantwebyastrights."
task :deploy_local do |t|
  mkdir_p "/etc/dbus-1/system.d/"
  cp_r    "package/example.service.conf", "/etc/dbus-1/system.d/"
  mkdir_p "/usr/local/sbin/"
  cp_r    "package/exampleService.rb", "/usr/local/sbin/"
  chmod  744, "/usr/local/sbin/exampleService.rb"
  mkdir_p "/usr/share/dbus-1/system-services/"
  cp_r    "package/example.service.service", "/usr/share/dbus-1/system-services/"
  `rake install_policies`
  `/usr/sbin/grantwebyastrights --user root --action grant --policy org.opensuse.yast.modules.yapi.example.read > /dev/null || :`
  `/usr/sbin/grantwebyastrights --user root --action grant --policy org.opensuse.yast.modules.yapi.example.write > /dev/null || :`
  command =  "/usr/sbin/grantwebyastrights --user #{ENV['USER']} --action grant --policy org.opensuse.yast.modules.yapi.example.read > /dev/null || :"
  puts command
  system command
  command =  "/usr/sbin/grantwebyastrights --user #{ENV['USER']} --action grant --policy org.opensuse.yast.modules.yapi.example.write > /dev/null || :"
  puts command
  system command
end

desc "Build distribution package (no check, for testing only)"
task :"package-local" do |t|
  `rake build`
  FileUtils.mv(Dir.glob("pkg/*.gem"), "package")
  FileUtils.rmdir("pkg")
end

require File.expand_path('../config/application', __FILE__)
Example::Application.load_tasks #   <<<< = require 'tasks/rails'

require "webyast-example"

require "bundler/gem_tasks"
task :build => :"gettext:pack"
