source 'http://rubygems.org'

gem 'rails', '3.1.1'

gem 'devise', '1.5.2'
gem 'devise_unix2_chkpwd_authenticatable', :path => File.expand_path("../../devise_unix2_chkpwd_authenticatable", __FILE__)
gem 'jquery-rails'
gem "sqlite3-ruby", :require => "sqlite3"

gem 'haml'
gem 'delayed_job', '2.1.4'

gem "fast_gettext", '>= 0.6.4'
gem 'gettext_i18n_rails', '>= 0.4.3'
gem 'nokogiri'
#only used for mo/po file generation in development, !do not load(:lib=>false)! since it will only eat 7mb ram
#Taking a special version due: http://stackoverflow.com/questions/7773408/very-strange-thing-with-rails-3-and-gettext-fast-gettext-undefined-method-ad
gem 'gettext',      :git=> 'https://github.com/cameel/gettext.git', :ref=> 'c3a8373',  :require => false

#this is needed for language/country translations
gem "countries_and_languages", '>=0.1.2', :require => 'countries_and_languages/rails'

gem 'ruby-debug'
gem 'cancan'
gem 'polkit1', :path => File.expand_path("../../ruby-polkit1", __FILE__)
gem 'inifile'
gem 'ruby-dbus'
gem 'uglifier'
gem 'execjs'
gem 'therubyracer'

plugin_path = File.expand_path("../../plugins",  __FILE__)
gemspecs = Dir.glob(File.join(plugin_path, "**", "*.gemspec"))
unless gemspecs.empty?
  #We are in devel. mode. Loading all plugins
  gemspecs.each do |gemspec|
    plugin_name = gemspec.split("/").pop.split(".")[0]
    gem plugin_name, 
        :path => File.expand_path("../../plugins/#{gemspec.split("/").pop(2)[0]}", __FILE__)
  end
else
  #Loading gems from the official path
  `gem list`.split("\n").each do |gem_name_version|
    gem_name = gem_name_version.split[0]
    gem gem_name if gem_name.start_with("webyast-")
  end 
end

group :development do
  # needed for rake gettext:find
  gem 'ruby_parser'
end

group :test do
  gem 'rspec', '>=2'
  gem 'rspec-rails', '>=2'
end

