source 'http://rubygems.org'

gem 'rails', '3.1.1'

gem 'devise'
# gem 'devise_pam_authenticatable', :git => 'git://github.com/jwilson511/devise_pam_authenticatable.git'

gem 'jquery-rails'
gem "sqlite3-ruby", :require => "sqlite3"

gem 'haml'

gem 'rpam', :git => 'git://gitorious.org/opensuse/ruby-rpam.git'
gem "fast_gettext", '>= 0.5'
gem 'gettext_i18n_rails'
gem 'nokogiri'
#only used for mo/po file generation in development, !do not load(:lib=>false)! since it will only eat 7mb ram
gem "gettext", '>= 1.9.3', :require => false

#this is needed for language/country translations
gem "countries_and_languages", '>=0.1.2', :require => 'countries_and_languages/rails'

group :test do
  gem 'rspec', '>=2'
  gem 'rspec-rails', '>=2'
end

