group :development do
  source 'http://rubygems.org'
end

gem 'rails', '~> 3.2.3'

gem 'devise', "~> 1.5.3"
gem 'devise-i18n'
gem 'devise_unix2_chkpwd_authenticatable'
gem 'cancan'

gem "sqlite3"

gem 'haml'

# SLES-11 contains ruby-dbus.rpm, while newer openSUSE distros have rubygem-ruby-dbus.rpm
# don't try loading the gem if there is plain ruby DBus library
gem "ruby-dbus" unless File.exists?("/usr/lib64/ruby/vendor_ruby/1.8/dbus.rb") || File.exists?("/usr/lib/ruby/vendor_ruby/1.8/dbus.rb")
gem 'delayed_job', '2.1.4'

gem 'nokogiri'
gem "fast_gettext", '>= 0.6.4'
gem 'gettext_i18n_rails', '>= 0.4.3'

gem 'inifile'
gem "builder"

#checking which policykit is used
WEBYAST_CONFIG_FILE = "/etc/webyast/config.yml"
if File.exist?(WEBYAST_CONFIG_FILE)
  values = YAML::load(File.open(WEBYAST_CONFIG_FILE, 'r').read)
  ENV['WEBYAST_POLICYKIT']= 'true' if values["polkit1"] == false
end

if ENV['WEBYAST_POLICYKIT']== 'true'
  gem 'polkit'
else
  gem 'polkit1'
end

plugin_path = File.expand_path("../../plugins",  __FILE__)
gemspecs = Dir.glob(File.join(plugin_path, "**", "*.gemspec"))

unless gemspecs.empty?
  #We are in devel. mode. Loading all plugins
  gemspecs.each do |gemspec|
    plugin_name = gemspec.split("/").pop.split(".").first
    gem plugin_name, :path => File.expand_path("../../plugins/#{gemspec.split("/").pop(2).first}", __FILE__)
  end
else
  #Loading webyast gems from the gem path
  Dir.glob(Gem.default_path.map{|p| File.join(p, "gems/webyast-*")}).each do |pth|
    # get gem name from path: /usr/lib64/ruby/gems/1.8/gems/webyast-users-0.1 => webyast-users
    gem File.basename(pth).split("-")[0..-2].join("-")
  end
end

group :development do
  gem 'gettext', :require => false
  # gem "ruby-debug"
  gem "factory_girl"
  gem 'ruby_parser' # needed for rake gettext:find
end

group :test do
  gem "factory_girl_rails"
  gem "mocha",  :require => false
end
