require File.join(File.dirname(__FILE__), 'config', 'rails_parent')
require File.join(RailsParent.parent, 'lib', 'tasks', 'common')

desc "Deploy for development - run db:migrate, create basic dirs and install grantwebyastrights."
task :deploy_local do |t|
  FileUtils.mkdir_p "/usr/share/YaST2/modules/"
  FileUtils.cp_r    "package/FIREWALL.pm", "/usr/share/YaST2/modules/YaPI"
  `rake install_policies`
end

desc "Build distribution package (no check, for testing only)"
task :"package-local" do |t|
  `rake build`
  FileUtils.mv(Dir.glob("pkg/*.gem"), "package")
  FileUtils.rmdir("pkg")
end

require File.expand_path('../config/application', __FILE__)
Firewall::Application.load_tasks #   <<<< = require 'tasks/rails'

require "webyast-firewall"

require "bundler/gem_tasks"
task :build => :"gettext:pack"
