require File.join(File.dirname(__FILE__), 'config', 'rails_parent')
require File.join(RailsParent.parent, 'lib', 'tasks', 'common')

desc "Deploy for development - run db:migrate, create basic dirs and install grantwebyastrights."
task :deploy_local do |t|
  FileUtils.mkdir_p "/usr/share/YaST2/modules/"
  FileUtils.cp_r    "package/FIREWALL.pm", "/usr/share/YaST2/modules/YaPI"
  FileUtils.mkdir_p "/usr/share/polkit-1/actions/"
  FileUtils.cp_r    "package/org.opensuse.yast.modules.yapi.firewall.policy",  "/usr/share/polkit-1/actions/"
end
