require 'rake'
require 'fileutils'
require File.join(File.dirname(__FILE__), 'config', 'rails_parent')
require File.join(RailsParent.parent, 'lib', 'tasks', 'common')

# Deploy ?!
desc "Deploy for development - create basic dirs and install yast modules."
task :deploy_local do |t|
  `rake install_policies`
end

desc "Build distribution package (no check, for testing only)"
task :"package-local" do |t|
  `rake build`
  FileUtils.mv(Dir.glob("pkg/*.gem"), "package")
  FileUtils.rmdir("pkg")
end

require File.expand_path('../config/application', __FILE__)
Network::Application.load_tasks #   <<<< = require 'tasks/rails'

require "webyast-network"

require "bundler/gem_tasks"
task :build => :"gettext:pack"

