require 'rake'
require 'rake/rdoctask'

# load the shared rake files from the package itself
# skip 'package-local' task, it's redefined here
require 'lib/tasks/webservice_tasks'
WebserviceTasks.loadTasks(:exclude => ["package-local.rake"])


# define clean and clobber tasks
require 'rake/clean'
CLEAN.include("package/*.spec", "package/*.gem")
CLOBBER.include("*.gem", "*.gemspec")
task :clobber => :clean


def read_version
    version = `cat VERSION`
    version.chomp
end

# generate a file from .in template, replace @VERSION@ string by VERSION file content
def version_update(filein, fileout = nil)
    if filein.nil? || filein.empty?
	puts "ERROR: empty input or output filename"
	exit 1
    end

    if fileout.nil? || fileout.empty?
	filein =~ /(.*)\.in$/
	fileout = $1
    end

    version = read_version

    puts "Updating #{fileout} (#{version})..."
    `sed -e 's|@VERSION@|#{version}|' #{filein} > #{fileout}`
end

# generate .gemspec file from the template
file "webyast-rake-tasks.gemspec" => ["webyast-rake-tasks.gemspec.in", "VERSION"] do
    version_update("webyast-rake-tasks.gemspec.in")
end


# generate RPM .spec file from the template
file "package/rubygem-webyast-rake-tasks.spec" => ["rubygem-webyast-rake-tasks.spec.in", "VERSION"] do
    version_update("rubygem-webyast-rake-tasks.spec.in", "package/rubygem-webyast-rake-tasks.spec")
end

# build the gem package
desc 'Build gem package, save RPM sources to package subdirectory'
task :"package-local" => [:clean,'webyast-rake-tasks.gemspec', 'package/rubygem-webyast-rake-tasks.spec'] do
    version = read_version
    sh 'gem build webyast-rake-tasks.gemspec' unless uptodate?("webyast-rake-tasks-#{version}.gem", FileList["lib/**/*"])
    cp "webyast-rake-tasks-#{version}.gem", "package"
end

desc 'Install webyast-rake-tasks gem package'
task :install do
    sh 'gem install webyast-rake-tasks'
end

desc 'Run test suite'
task :test do
    puts 'no test yet'
end
# vim: ft=ruby
