require 'rake'
require 'fileutils'
require File.join(File.dirname(__FILE__), 'config', 'rails_parent')
require File.join(RailsParent.parent, 'lib', 'tasks', 'common')

desc 'Deploy for development - install yast modules.'
task :deploy_local do |t|
  FileUtils.mkdir_p "/usr/share/YaST2/modules/YaPI/"
  FileUtils.cp "package/MailSettings.pm", "/usr/share/YaST2/modules/YaPI"
  `rake install_policies`
end

desc "Build distribution package (no check, for testing only)"
task :"package-local" do |t|
  `rake build`
  FileUtils.mv(Dir.glob("pkg/*.gem"), "package")
  FileUtils.rmdir("pkg")
end

require File.expand_path('../config/application', __FILE__)
Mailsetting::Application.load_tasks #   <<<< = require 'tasks/rails'

require "webyast-mailsetting"

require "bundler/gem_tasks"
task :build => :"gettext:pack"

create_online_help_task "Mail"

task :restdoc_dir do
  restdoc_target = "public/restdoc/mailsetting"
  if !File.exist? restdoc_target
    puts "Creating directory #{restdoc_target}"
    FileUtils.mkdir_p restdoc_target
  end
end

task :restdoc => :restdoc_dir

