require File.join(File.dirname(__FILE__), 'config', 'rails_parent')
require File.join(RailsParent.parent, 'lib', 'tasks', 'common')

desc "Deploy for development - run db:migrate, create basic dirs and install grantwebyastrights."
task :deploy_local do |t|
  FileUtils.mkdir_p "/usr/share/YaST2/modules/"
  FileUtils.cp_r    "package/NTP.pm", "/usr/share/YaST2/modules/YaPI"
  `rake install_policies`
end

require File.expand_path('../config/application', __FILE__)
Ntp::Application.load_tasks #   <<<< = require 'tasks/rails'
