require 'rake'
require 'fileutils'
require File.join(File.dirname(__FILE__), 'config', 'rails_parent')
require File.join(RailsParent.parent, 'lib', 'tasks', 'common')

desc "Deploy for development - run db:migrate, create basic dirs and install grantwebyastrights."
task :deploy_local do |t|
  FileUtils.mkdir_p "/usr/share/YaST2/modules/"
  FileUtils.cp_r    "package/NTP.pm", "/usr/share/YaST2/modules/YaPI"
  `rake install_policies`
end

desc "Build distribution package (no check, for testing only)"
task :"package-local" => :build do |t|
  FileUtils.mv(Dir.glob("pkg/*.gem"), "package")
  FileUtils.rmdir("pkg")
end

require File.expand_path('../config/application', __FILE__)
Ntp::Application.load_tasks #   <<<< = require 'tasks/rails'

require "webyast-ntp"

require "bundler/gem_tasks"

task :clean_gems do
  FileUtils.rm Dir.glob("package/*.gem")
end

task :build => [:"gettext:pack", :clean_gems]

task :restdoc_dir do
  restdoc_target = "public/restdoc/ntp"
  if !File.exist? restdoc_target
    puts "Creating directory #{restdoc_target}"
    FileUtils.mkdir_p restdoc_target
  end
end

task :restdoc => :restdoc_dir

