require 'rake'
require 'fileutils'

require File.join(File.dirname(__FILE__), 'config', 'rails_parent')
require File.join(RailsParent.parent, 'lib', 'tasks', 'common')

# Deploy ?!
desc "Deploy for development - create basic dirs and install yast modules."
task :deploy_local do |t|
  `rake install_policies`
end

desc "Build distribution package (no check, for testing only)"
task :"package-local" => :build do |t|
  FileUtils.mv(Dir.glob("pkg/*.gem"), "package")
  FileUtils.rmdir("pkg")
end

require File.expand_path('../config/application', __FILE__)
Kerberos::Application.load_tasks #   <<<< = require 'tasks/rails'

require "webyast-kerberos"

require "bundler/gem_tasks"

task :clean_gems do
  FileUtils.rm Dir.glob("package/*.gem")
end

task :build => [:"gettext:pack", :clean_gems]

create_online_help_task "Kerberos"

task :restdoc_dir do
  restdoc_target = "public/restdoc/kerberos"
  if !File.exist? restdoc_target
    puts "Creating directory #{restdoc_target}"
    FileUtils.mkdir_p restdoc_target
  end
end

task :restdoc => :restdoc_dir

