#--
# Copyright (c) 2009-2010 Novell, Inc.
#
# All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of version 2 of the GNU General Public License
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, contact Novell, Inc.
#
# To contact Novell about this file by physical or electronic mail,
# you may find current contact information at www.novell.com
#++

require 'rake'
require 'fileutils'
require File.join(File.dirname(__FILE__), 'config', 'rails_parent')
require File.join(RailsParent.parent, 'lib', 'tasks', 'common')

desc "Deploy for development - create basic dirs and install config files."
task :deploy_local do |t|
  FileUtils.mkdir_p "/etc/webyast"
  FileUtils.mkdir_p "/var/lib/webyast/eulas/accepted-licenses"
  FileUtils.mkdir_p "/usr/share/webyast/eulas"
  FileUtils.install "package/eulas-sles11.yml", "/etc/webyast/eulas.yml", :mode => 0644
  FileUtils.cp_r    "config/resources/licenses", "/usr/share/webyast/eulas"
  FileUtils.mkdir_p "/usr/share/polkit-1/actions/"
  FileUtils.cp_r    "package/org.opensuse.yast.modules.yapi.license.policy",  "/usr/share/polkit-1/actions/"
end

desc "Build distribution package (no check, for testing only)"
task :"package-local" do |t|
  `rake build`
  FileUtils.mv(Dir.glob("pkg/*.gem"), "package")
  FileUtils.rmdir("pkg")
end

require File.expand_path('../config/application', __FILE__)
Eulas::Application.load_tasks #   <<<< = require 'tasks/rails'

require "webyast-administrator"

require "bundler/gem_tasks"
task :build => :"gettext:pack"
