require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/packagetask'
require File.join(File.dirname(__FILE__), 'config', 'rails_parent')
require File.join(RailsParent.parent, 'config', 'boot')

# load the shared rake files from the package itself
# skip 'deploy_local' task, it's redefined here
require 'tasks/webservice_tasks'
WebserviceTasks.loadTasks(:exclude => ["deploy_local.rake"])

# this call also loads WebserviceTasks but the second call is ignored there
# so this 'require' must be called _after_ WebserviceTasks.loadTasks
require 'tasks/rails'

desc 'Default: run unit tests.'
task :default => :test

require 'fileutils'

desc "Deploy for development - create basic dirs and install config files."
task :deploy_local do |t|
  FileUtils.mkdir_p "/etc/webyast"
  FileUtils.mkdir_p "/var/lib/yastws/eulas/accepted-licenses"
  FileUtils.mkdir_p "/usr/share/yastws/eulas"
  FileUtils.install "package/eulas-sles11.yml", "/etc/webyast/eulas.yml", :mode => 0644
  FileUtils.cp_r    "config/resources/licenses", "/usr/share/yastws/eulas"
end
