#--
# Copyright (c) 2009-2010 Novell, Inc.
# 
# All Rights Reserved.
# 
# This program is free software; you can redistribute it and/or modify it
# under the terms of version 2 of the GNU General Public License
# as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, contact Novell, Inc.
# 
# To contact Novell about this file by physical or electronic mail,
# you may find current contact information at www.novell.com
#++
require File.join(File.dirname(__FILE__), 'config', 'rails_parent')
require File.join(RailsParent.parent, 'lib', 'tasks', 'common')

include FileUtils::Verbose

#adapt to easyli local deploy of working plugin (for developement, release use rpm-based way)
desc "Deploy for development - run db:migrate, create basic dirs and install grantwebyastrights."
task :deploy_local, [:user] do |t, args|
  args.with_defaults :user => user = ENV['USER']
  `rake install_policies`
  mkdir_p "/var/lib/webyast/roles/"
  cp_r    "package/roles.yml", "/var/lib/webyast/roles/" unless File.exists? "/var/lib/webyast/roles/roles.yml"
  cp_r    "package/roles_assign.yml", "/var/lib/webyast/roles/" unless File.exists? "/var/lib/webyast/roles/roles_assign.yml"
  chmod 0700, "/var/lib/webyast/roles/"
  chmod 0600, "/var/lib/webyast/roles/roles.yml"
  chmod 0600, "/var/lib/webyast/roles/roles_assign.yml"
  chown args.user, nil, "/var/lib/webyast/roles/"
  chown args.user, nil, "/var/lib/webyast/roles/roles.yml"
  chown args.user, nil, "/var/lib/webyast/roles/roles_assign.yml"
end
