#--
# Copyright (c) 2009-2010 Novell, Inc.
# 
# All Rights Reserved.
# 
# This program is free software; you can redistribute it and/or modify it
# under the terms of version 2 of the GNU General Public License
# as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, contact Novell, Inc.
# 
# To contact Novell about this file by physical or electronic mail,
# you may find current contact information at www.novell.com
#++

require File.join(File.dirname(__FILE__), 'config', 'rails_parent')
require File.join(RailsParent.parent, 'lib', 'tasks', 'common')

#import rake task files from plugins directory 
Dir.glob(File.dirname(__FILE__) + "/lib/tasks/*.rake").each do |rake_file|
  import rake_file
end

desc "Deploy for development - create basic dirs and install yast modules."
task :deploy_local do |t|
  FileUtils.mkdir_p "/usr/share/YaST2/modules/"
  FileUtils.cp_r    "package/LogFile.rb", "/usr/share/YaST2/modules/"
  `rake install_policies`
end

require File.expand_path('../config/application', __FILE__)
Status::Application.load_tasks #   <<<< = require 'tasks/rails'
