require File.join(File.dirname(__FILE__), 'config', 'rails_parent')
require File.join(RailsParent.parent, 'lib', 'tasks', 'common')

desc "Deploy for development - create basic dirs and install yast modules."
task :deploy_local do |t|
  FileUtils.mkdir_p "/usr/share/YaST2/modules/"
  FileUtils.cp_r    "package/LogFile.rb", "/usr/share/YaST2/modules/"
  FileUtils.mkdir_p "/usr/share/PolicyKit/policy/"
  FileUtils.cp_r    "package/org.opensuse.yast.modules.logfile.policy",  "/usr/share/PolicyKit/policy/"
  FileUtils.cp_r    "package/org.opensuse.yast.system.status.policy",  "/usr/share/PolicyKit/policy/"
end

