require File.join(File.dirname(__FILE__), 'config', 'rails_parent')
require File.join(RailsParent.parent, 'lib', 'tasks', 'common')

include FileUtils::Verbose

# Deploy ?!
desc "Deploy for development - install necessary files for users plugin."
task :deploy_local do |t|
  mkdir_p "/usr/share/PolicyKit/policy/"
  cp_r    "package/org.opensuse.yast.modules.yapi.users.policy", "/usr/share/PolicyKit/policy/"
end
