$: << File.join(File.dirname(__FILE__), "lib")

require "bundler/gem_tasks"
require 'rake/testtask'

task :default => [:compile, :test, :build, :package]

gem 'rake-compiler', '>= 0.4.1'
require 'rake/extensiontask'
Rake::ExtensionTask.new('polkit1')

task :package do
  FileUtils.cp Dir.glob("pkg/*.gem")[0].to_s, "package/"
end

Rake::TestTask.new do |t|
  t.libs << File.expand_path('../test', __FILE__)
  t.libs << File.expand_path('../', __FILE__)
  t.test_files = FileList['test/test*.rb']
  t.verbose = true
end

extra_docs = ['README*', 'CHANGELOG*']

begin
 require 'yard'
  YARD::Rake::YardocTask.new(:doc) do |t|
    t.files   = ['lib/**/*.rb', *extra_docs]
    t.options = ['--no-private']
  end
rescue LoadError
  STDERR.puts "Install yard if you want prettier docs"
  require 'rdoc/task'
  Rake::RDocTask.new(:doc) do |rdoc|
    rdoc.rdoc_dir = "doc"
    rdoc.title = "polkit1 #{PolKit1::VERSION}"
    extra_docs.each { |ex| rdoc.rdoc_files.include ex }
  end
end
