require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/packagetask'
require File.join(File.dirname(__FILE__), 'config', 'rails_parent')
require File.join(RailsParent.parent, 'config', 'boot')

# try the local (development) webservice_tasks copy first
begin
  require File.join(RailsParent.parent, '..', 'webservice-tasks', 'lib', 'tasks', 'webservice_tasks')
rescue LoadError
  begin
    require 'tasks/webservice_tasks'
  rescue LoadError
    $stderr.puts "Install rubygem-webyast-rake-tasks"
    exit 1
  end
end

# load the shared rake files from the package itself
# skip 'deploy_local' task, it's redefined here
WebserviceTasks.loadTasks(:exclude => ["deploy_local.rake"])

# this call also loads WebserviceTasks but the second call is ignored there
# so this 'require' must be called _after_ WebserviceTasks.loadTasks
require 'tasks/rails'

desc 'Default: run unit tests.'
task :default => :test

require 'fileutils'

desc 'Deploy for development - create basic dirs and install config files.'
task :deploy_local do |t|
  FileUtils.mkdir_p "/etc/webyast"
  FileUtils.mkdir_p "/var/lib/yastws/basesystem"
  FileUtils.cp "package/basesystem.yml", "/etc/webyast"
end
