require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/packagetask'
require File.join(File.dirname(__FILE__), 'config', 'rails_parent')
require File.join(RailsParent.parent, 'config', 'boot')
require 'tasks/rails'
# load the shared rake files from the package itself
# skip 'deploy_local' task, it's redefined here
require 'tasks/webservice_tasks'
WebserviceTasks.loadTasks(:exclude => ["deploy_local.rake"])

desc 'Default: run unit tests.'
task :default => :test

desc 'Deploy for development - install yast modules.'
task :deploy_local do |t|
  FileUtils.mkdir_p "/usr/share/YaST2/modules/YaPI/"
  FileUtils.cp "package/MailSettings.pm", "/usr/share/YaST2/modules/YaPI"
end
