require "polkit1/version"
require 'polkit1.so' # native
require 'etc'

module PolKit1
  POLKIT_PATH = "/etc/polkit-1/rules.d/"
  FILE_PREFIX = "10-webyast-"

  def self.polkit1_check(perm, user_name)
    raise "invalid user name" if (user_name =~ /\\$/ or user_name.include? "'")
    polkit1_check_uid perm, Etc.getpwnam(user_name).uid
  end

  def self.polkit1_write(section, perm, granted, user_name)
    raise "invalid user name" if (user_name =~ /\\$/ or user_name.include? "'")
    #raise "section name required" if section.empty?
    raise "user name required" if user_name.empty?

    # TODO: is section (subdir) supported by new polkit??
    file = File.join(POLKIT_PATH, FILE_PREFIX + perm.gsub(".", "_") + ".rule")

    if granted
      content = "
//
// This polkit authorization rule was created by WebYast
//
// !! WARNING: DO NOT EDIT THIS FILE !!
//
//

polkit.addRule(function(action, subject) {
  if (action.id == \"#{perm}\" &&
    subject.user == \"#{user_name}\")
  {
    return polkit.Result.YES;
  }
});
"
      File.open(file, "w") do |f|
        f.puts content
      end
    else
      File.delete(file) if File.exist?(file)
    end
  end

end

