# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

#include in doc:app also shared test enhancements for plugins
#FIXME find way how to change original rails task app:doc we only need include some files to it
namespace :doc do
  Rake::RDocTask.new("app") { |rdoc|
    rdoc.rdoc_dir = 'doc/app'
    rdoc.title    = "Rails Application Documentation"
    rdoc.options << '--line-numbers' << '--inline-source'
    rdoc.rdoc_files.include('doc/README_FOR_APP')
    rdoc.rdoc_files.include('app/**/*.rb')
    rdoc.rdoc_files.include('lib/**/*.rb')
#include shared test functionality in documentation
    rdoc.rdoc_files.include('test/plugin_basic_tests.rb')
  }
end

# load the shared rake files from the package itself
# skip 'deploy_local' task, it's redefined here
require 'tasks/webservice_tasks'
WebserviceTasks.loadTasks(:exclude => ["deploy_local.rake"])

require 'fileutils'

desc "Deploy for development - run db:migrate, create basic dirs and install grantwebyastrights."
task :deploy_local => :"db:migrate" do |t|
  FileUtils.mkdir_p "/etc/webyast"
  FileUtils.mkdir_p "/var/lib/yastws"
  FileUtils.mkdir_p "/usr/share/yastws"
  FileUtils.install "package/grantwebyastrights", "/usr/sbin", :mode => 0555
  system "/usr/bin/polkit-auth --user root --grant org.opensuse.yast.module-manager.import > /dev/null"
  system "/usr/bin/polkit-auth --user root --grant org.freedesktop.policykit.read > /dev/null"
  system "/usr/bin/polkit-auth --user root --grant org.freedesktop.packagekit.system-update > /dev/null"
end

